<a href="https://colab.research.google.com/github/BALANJANEYULU-799/ML-ASSIGNMENTS/blob/main/MLassignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.
Perform arithmetic operations on NumPy arrays.

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,5,4],[3,2,1]])
print("a=\n",a)
print("b=\n",b)
print("a+b\n",a+b)

a=
 [[1 2 3]
 [4 5 6]]
b=
 [[6 5 4]
 [3 2 1]]
a+b
 [[7 7 7]
 [7 7 7]]


2.
Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
import numpy as np
a=np.array([6,7,8,9,14,18])
sum=0
for i in a:
  sum=sum+i;
n=a.size
print("mean=",(sum/n))
print("standard deviation=",np.std(a))

mean= 10.333333333333334
standard deviation= 4.268749491621899


Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
import numpy as np
a=np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


4.
Reshape the array into a 2x4 matrix.

In [ ]:
import numpy as np
arr=np.array([9,8,7,6,5,4,3,2])
resize=arr.reshape(2,4)
print(resize)

[[9 8 7 6]
 [5 4 3 2]]


5.
Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
•
Extract the sub-matrix containing the last two rows and first two columns.
•
Replace all elements greater than 4 with 0.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("array=\n",arr)
a=arr[1:,1:]
print("sub matrix=\n",a)
arr[arr>4]=0
print("replaced matrix=\n",arr)

array=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sub matrix=
 [[5 6]
 [8 9]]
replaced matrix=
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


6.
Create two 1D arrays:
•
a = np.array([1, 2, 3])
•
b = np.array([4, 5, 6])
•
Perform element-wise addition, multiplication, and division.

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("addition:\n",a+b)
print("mutiplication:\n",a*b)
print("division:\n",a/b)

addition:
 [5 7 9]
mutiplication:
 [ 4 10 18]
division:
 [0.25 0.4  0.5 ]


Create a random NumPy array of size (4, 4). Compute:
•
Mean of each column.
•
Maximum value of the entire array.
•
Sum of all elements.

In [ ]:
import numpy as np
array=np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print("max:",np.max(array))
c0 = array[:, 0]
c1 = array[:, 1]
c2 = array[:, 2]
c3= array[:, 3]
print("mean of c1:",np.mean(c0))
print("mean of c2:",np.mean(c1))
print("mean of c3:",np.mean(c2))
print("mean of c4:",np.mean(c3))
print("sum:",np.sum(array))

max: 8
mean of c1: 4.5
mean of c2: 4.5
mean of c3: 4.5
mean of c4: 4.5
sum: 72


8.
Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print("adding 10",arr+10)
print("multiply by 2",arr*2)

adding 10 [11 12 13 14]
multiply by 2 [2 4 6 8]


9.
Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:
•
Extract the second "layer" (i.e., the second 2D array) in the first dimension.
•
Extract the first two rows and the last three columns from each "layer."
•
Replace all elements divisible by 3 with -1.

In [ ]:
import numpy as np
arr=np.random.randint(1,101,size=(3,4,5))
print(arr)
arr2=arr[:,:2,:3]
print("sliced array:\n",arr2)
arr[arr%3==0]=-1
print("replaced array:\n",arr)

[[[ 38  92  66  53  11]
  [  3   7  52  60  42]
  [ 88  67  74  25 100]
  [ 20   2  57  90  15]]

 [[ 61   6  57  59  27]
  [ 68  27  69  62  50]
  [ 26  12  89  60  80]
  [ 14  81  49  81  25]]

 [[ 50  80  82  71  26]
  [ 56  91 100  80  17]
  [ 15  25  11  11  90]
  [100  87  44  49  66]]]
sliced array:
 [[[ 38  92  66]
  [  3   7  52]]

 [[ 61   6  57]
  [ 68  27  69]]

 [[ 50  80  82]
  [ 56  91 100]]]
replaced array:
 [[[ 38  92  -1  53  11]
  [ -1   7  52  -1  -1]
  [ 88  67  74  25 100]
  [ 20   2  -1  -1  -1]]

 [[ 61  -1  -1  59  -1]
  [ 68  -1  -1  62  50]
  [ 26  -1  89  -1  80]
  [ 14  -1  49  -1  25]]

 [[ 50  80  82  71  26]
  [ 56  91 100  80  17]
  [ -1  25  11  11  -1]
  [100  -1  44  49  -1]]]


10. Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between
1 and 20. Perform the following:
•
Subtract the mean of each row from its respective elements (row-wise normalization).
•
Create a new array by squaring all the elements in arr.
•
Find the indices of the top 3 maximum values in the entire array.

In [1]:
import numpy as np
a=np.random.randint(1,20,size=(3,3))
print(a)
print("after subtracting mean:\n")
row1=a[0:1]-np.mean(a[0:1])
row2=a[1:2]-np.mean(a[1:2])
row3=a[2:3]-np.mean(a[2:3])
print(row1,"\n",row2,"\n",row3)
b=a*a
print("squarred array:\n",b)
top_indices = np.argsort(a, axis=None)[-3:]


top_2d_indices = np.unravel_index(top_indices, a.shape)


print("Top 3 indices:", list(zip(top_2d_indices[0], top_2d_indices[1])))
print("Top 3 values:", a[top_2d_indices])





[[18 16 14]
 [ 5 11 12]
 [16 17  1]]
after subtracting mean:

[[ 2.  0. -2.]] 
 [[-4.33333333  1.66666667  2.66666667]] 
 [[  4.66666667   5.66666667 -10.33333333]]
squarred array:
 [[324 256 196]
 [ 25 121 144]
 [256 289   1]]
Top 3 indices: [(2, 0), (2, 1), (0, 0)]
Top 3 values: [16 17 18]
